### ISSUE TITLE
the URLs of naturalearth download are no longer valid

### ISSUE THREAD

**Issue by danduk82** [danduk82/foss4g2021#18]
hem, @bchapuis I just wanted to test the naturalearth example, and it seems that naciscdn.org does not exist anymore.

on their [download page](https://www.naturalearthdata.com/downloads/) all the URLs are striked...

**Comment by bchapuis** [comment]
Yes, the url has been updated in the baremaps/baremaps repo but not yet in the baremaps/openstreetmap-vecto repo.

**Comment by bchapuis** [comment]
Here is the correct url:
https://naturalearth.s3.amazonaws.com/packages/natural_earth_vector.sqlite.zip
